export const ICONS = {
    ETH_MONO: "eth_mono",
    MATIC_MONO: "matic_mono",
    BSC_MONO: "bsc_mono",
    SEARCH: "search",
    KEY: "key",
    ROCKET: "rocket",
    ALERT: "alert-circle",
    CHECKMARK: "checkmark",
    CALCULATOR: "calculator",
    DIAMOND: "diamond",
    WAIT: "wait",
    WHALE: "whale",
    LOCK: "lock",
    CANCEL: "cancel",
    CANCEL_OUTLINE: "cancel-outline",
    SUCCESS: "success-outline",
    INFO: "info",
    TICKET: "ticket",
};
