export const PhaseId = {
    Whale: 1,
    Pending: 2,
    Raffle: 3,
    Open: 4,
    FCFS: 5,
    UnlimitedSlow: 6,
    Unlimited: 7,
    Closed: 8,
};

export const Phases = {
    [PhaseId.Whale]: {
        phase: PhaseId.Whale,
        phaseName: "Whale",
        phaseDescription: "Exclusive phase for large investors. Opening soon.",
        button: "Open Soon",
        controlsDisabled: true,
        startDate: 0,
    },
    [PhaseId.Pending]: {
        phase: PhaseId.Pending,
        phaseName: "Pending",
        phaseDescription: "Phase is being prepared. Users can register for the raffle during this time.",
        button: "Open Soon",
        controlsDisabled: true,
        startDate: 0,
    },
    [PhaseId.Raffle]: {
        phase: PhaseId.Raffle,
        phaseName: "Raffle",
        phaseDescription: "Raffle winners have guaranteed allocation.",
        button: "Open Soon",
        controlsDisabled: true,
        startDate: 0,
    },
    [PhaseId.Open]: {
        phase: PhaseId.Open,
        phaseName: "Open",
        phaseDescription: "Investment is open to all users. Limited time availability.",
        button: "Invest",
        controlsDisabled: false,
        startDate: -1,
    },
    [PhaseId.FCFS]: {
        phase: PhaseId.FCFS,
        phaseName: "FCFS",
        phaseDescription: "Investment is open but capped. First come, first served access.",
        button: "Invest",
        controlsDisabled: false,
        startDate: -1,
    },
    [PhaseId.UnlimitedSlow]: {
        phase: PhaseId.UnlimitedSlow,
        phaseName: "Unlimited slow",
        phaseDescription: "Investments are open with a capped limit per user.",
        button: "Invest",
        controlsDisabled: false,
        startDate: -1,
    },
    [PhaseId.Unlimited]: {
        phase: PhaseId.Unlimited,
        phaseName: "Unlimited",
        phaseDescription: "Unlimited investment phase with no restrictions.",
        button: "Invest",
        controlsDisabled: false,
        startDate: -1,
    },
    [PhaseId.Closed]: {
        phase: PhaseId.Closed,
        phaseName: "Closed",
        phaseDescription: "The investment opportunity has ended. No further investments allowed.",
        button: "Closed",
        controlsDisabled: true,
        startDate: -1,
    },
};
