name: Docker Image Pre-Merge CI

on:
  pull_request:
    branches: '*'

jobs:
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
#
#      - name: Create Placeholder .env file
#        run: |
#          touch .env
#          touch .kubeconfig
#
#      - name: Set up Docker Buildx
#        uses: docker/setup-buildx-action@v1
#
#      - name: Cache Docker layers
#        uses: actions/cache@v2
#        with:
#          path: /tmp/.buildx-cache
#          key: ${{ runner.os }}-buildx-${{ github.sha }}
#          restore-keys: |
#            ${{ runner.os }}-buildx-
#
#      - name: Build Docker image
#        run: |
#          docker build -t my-image:${{ github.sha }} .
